FROM balenalib/%%BALENA_MACHINE_NAME%%-node

WORKDIR /usr/src/app

COPY package.json /package.json
RUN JOBS=MAX npm install --production --unsafe-perm && npm cache verify && rm -rf /tmp/*
# Build the app for production in the `build` folder

COPY src/ /usr/src/app
COPY public/ /usr/src/app/
CMD ["node", "/usr/src/app/main.js"]

# Deploy the app
# serve -s build -l 80